### ISSUE TITLE
[IDEA] Define button colours in every palette

### ISSUE THREAD

**Issue by Vingolf** [TiddlyWiki/TiddlyWiki5#5153]
**Is your feature request related to a problem? Please describe.**
The combination of undefined button colours of some palettes<br> can cause confusing results<br> in combination with the emphasized theme and the tinka plugin.<br>(a white font on a white background color). <br>

**Screenshots**
See 
[Emphasized theme and Tinka plugin style](https://groups.google.com/g/tiddlywiki/c/TLPFazvTzNQ/m/J9hG6yeZAAAJ)

**Describe the solution you'd like**
Defining button colours

```
button-background: <<colour background>>
button-foreground: <<colour foreground>>
```
in every core palette can be a way to solve such issues.

**To Reproduce**

1.  Use a Tiddlywiki empty (tested with 5.1.21; <br>5.1.22 and 5.1.23-p are expected to show similar results)
2. Drag and drop [Emphasized theme 0.0.17](http://tongerner.tiddlyspot.com/#Emphasized%20theme) into this wiki. Import, save and reload.
3. Drag and drop [Tinka 0.5.0](https://tinkaplugin.github.io/#%24%3A%2Fplugins%2Fahahn%2Ftinka) into this wiki. Import, save and reload.
4. Open $:/ControlPanel/Tinka Plugin Management tab/Modify Plugins tab
5. Button texts are invisible having white fonts on a white button colour background.

**Expected behavior**
I expect the text on this buttons can be read with every palette.

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro
 - Browser: Firefox
 - Version 83.0

**Comment by Jermolene** [comment]
Hi @Vingolf leaving the button colours undefined causes browsers to retain their base styling to make the buttons match the underlying operating system. The OS-style buttons are generally preferred because they meet user expectations for the look and behaviour of buttons.

For example, here is an iPad with the "Vanilla" palette, where the buttons look like buttons:

![image](https://user-images.githubusercontent.com/174761/100644275-05e25600-3333-11eb-9eb1-c1961e95604f.png)

And here is the same screen with the "Spartan Night" palette, where the buttons lose the appearance of being clickable:

![image](https://user-images.githubusercontent.com/174761/100644408-2f9b7d00-3333-11eb-8203-08aab76e612c.png)

**Comment by pmario** [comment]
@Vingolf -- I think the main problem here are the styles that are used by the them and not the TW palettes. 

tiddlywiki.com Stylesheet overview looks like this: 

![image](https://github.com/user-attachments/assets/e65a2afe-e4f8-413c-adf8-439bd65777dd)

The Emphasized theme  it looks like this. See: http://tongerner.tiddlyspot.com/#%24%3A%2Fcore%2Fui%2FControlPanel%2FStylesheets

So it seems many of the core values have been overwritten by: http://tongerner.tiddlyspot.com/#%24%3A%2Fthemes%2Ftg%2Femphasized%2Fstyles

![image](https://github.com/user-attachments/assets/fcbc1982-21ce-42de-a748-d70af8e0fe9d)

So the way to go is: Fixing the Emphasized theme. 

@Jermolene -- IMO this one may be closed. I think we can not do much here
