### ISSUE TITLE
[IDEA] Pragmas allowed everywhere, not just at start of parsing context

### ISSUE THREAD

**Issue by rmunn** [TiddlyWiki/TiddlyWiki5#7680]
**Is your feature request related to a problem? Please describe.**
The idea of an if...else or if...then...else construct has been brought up several times. As part of that discussion, @Jermolene proposed an [`\if` ... `\else` ... `\endif` pragma](https://talk.tiddlywiki.org/t/switch-case-construct/2234/13), which would necessarily require that [pragmas would be allowed anywhere in wikitext](https://talk.tiddlywiki.org/t/switch-case-construct/2234/20), except for the `\rules` pragma which would still need to appear at the top of a tiddler.

There are several use cases that this would allow:
* `\if`...`\else`...`\endif`
* `\switch`...`\case`...`\case`...`\default`...`\endswitch`
* Defining procedures/functions/custom widgets in the middle of a tiddler
* Probably many others

Since this idea would be broadly useful, I think it's worth tracking the idea in a GitHub issue.

**Describe the solution you'd like**
The WikiText parser is rewritten to allow pragmas to appear anywhere, except for the ones that change the parser rules

**Describe alternatives you've considered**
The `\if` and `\swtich` use cases could be done with widgets instead:

```plaintext
<$if filter="condition">
  <$then>Value if true</$then>
  <$else>Value if false</$else>
</$if>

<$switch filter="value to test">
  <$case filter="one">Result if one</$case>
  <$case filter="two">Result if two</$case>
  <$default>Result if no match</$default>
</$switch>
```

See https://github.com/Jermolene/TiddlyWiki5/issues/6862#issuecomment-1200449657 for the source of this idea.

However, there is currently no way to define procedures, custom widgets, and so on in the middle of a tiddler, so no alternative exists for this one.

**Additional context**
Previous discussion of the if...else or switch widgets (or closely related ideas):
* https://github.com/Jermolene/TiddlyWiki5/issues/272
* https://github.com/Jermolene/TiddlyWiki5/issues/1248
* https://github.com/Jermolene/TiddlyWiki5/issues/3463
* https://github.com/Jermolene/TiddlyWiki5/issues/4064
* https://talk.tiddlywiki.org/t/switch-case-construct/2234
* https://github.com/Jermolene/TiddlyWiki5/issues/6862

Clearly there's demand for this, and I think the `\if` ... `\else` pragma is probably the most useful of the proposed implementations. That would require pragmas to be allowed everywhere, hence this issue which tracks that prerequisite work.

**Comment by rmunn** [comment]
I just now realized that there's a drawback to the syntax proposed in (link):

```plaintext
<$if filter="condition">
  <$then>Value if true</$then>
  <$else>Value if false</$else>
</$if>
```

This allows no easy way to do an `elseif`. For example, the following pseudo-code:

* If `n` divisible by 15, output "FizzBuzz"
* Else if `n` divisible by 5, output "Buzz"
* Else if `n` divisible by 3, output "Fizz"
* Else output `n`

Would turn into the following in that widget syntax:

```plaintext
<$if filter="[<n>divisibleBy[15]]">
  <$then>FizzBuzz</$then>
  <$else>
    <$if filter="[<n>divisibleBy[5]]">
      <$then>Buzz</$then>
      <$else>
        <$if filter="[<n>divisibleBy[3]]">
          <$then>Fizz</$then>
          <$else><<n>></$else>
        </$if>
      </$else>
    </$if>
  </$else>
</$if>
```

Using a pragma syntax, those extra levels of nesting could be avoided, producing a much easier to read result:

```plaintext
\if [<n>divisibleBy[15]]
FizzBuzz
\elseif [<n>divisibleBy[5]]
Buzz
\elseif [<n>divisibleBy[3]]
Fizz
\else
<<n>>
\endif
```

So there's a good reason to prefer the pragma syntax of `\if` ... `\elseif` ... `\else`, and therefore pragmas (well, *most* pragmas) do need to be allowable everywhere.

**Comment by pmario** [comment]
Pragmas at the moment are parsed at the very beginning of each tiddler. They are simple and fast to parse, because we exactly know, where they start an where they end. They are set to variables with a scope of the currentTiddler.

Having pragmas in between wikitext it would be needed to parse the whole text 2 or even more times. I do see a fatal performance hit, if it is implemented as real pragmas. 

If `\if xx` would be a shortcut for a widget call, than we should use widget calls instead because of consistency.

**Comment by rmunn** [comment]
> If `\if xx` would be a shortcut for a widget call, than we should use widget calls instead because of consistency.

The problem is that `\elseif` cannot be directly represented in widget syntax, as I tried to show with the FizzBuzz example. So the pragma syntax is necessary for an if...elseif...else...endif construct.

**Comment by Jermolene** [comment]
Thanks for the insights @rmunn. I think that "elseif" could be implemented at the widget level, but the nesting in your fizz buzz example is unavoidable with the widget approach. It might be done something like this:

```
<$if filter="[<n>divisibleBy[15]]">
<$then>
FizzBuzz
</$then>
<$elseif filter="[<n>divisibleBy[5]]">
Buzz
</$elseif>
<$elseif filter="[<n>divisibleBy[3]]">
Fizz
</$elseif>
<$else>
<<n>>
</$else>
</$if>
```

This syntax much more verbose than the pragma example, but consistent and practical. It relies on an implementation of the "if" widget that scans and processes its child widgets consecutively until it finds one that can be displayed.

The way to tackle the verbosity is to provide a wikitext shortcut syntax. I'm not sure that the pragma syntax is the best choice because (a) it is block mode only, and doesn't support inline usage and (b) from an implementation perspective, extra work would be needed to get things working with the "importvariables" widget which doesn't currently process anything except "set" widgets.

So as discussed recently in one of the other threads, I think the position is that we have a viable widget layer approach, but need a new idea for the wikitext shortcut syntax.

**Comment by pmario** [comment]
@rmunn ... Can this issue be closed? With the implementation of if-then-else in v5.3.2 we know how the mechanism needs to be. It won't be implemented as proposed.

**Comment by pmario** [comment]
@rmunn ... Can this issue be closed? With the implementation of if-then-else in v5.3.2 we know how the mechanism needs to be. It won't be implemented as proposed.

**Comment by Jermolene** [comment]
Thanks @rmunn @pmario
