### ISSUE TITLE
[IDEA] Add variable holding title of tiddler in viewport

### ISSUE THREAD

**Issue by twMat** [TiddlyWiki/TiddlyWiki5#8478]
I want an accessible variable with the *title of the tiddler currently seen in viewport*.

There exists such a plugin by @Gk0Wk [focused-tiddler](https://tw-cpl.netlify.app/#%24%3A%2Fplugins%2FGk0Wk%2Ffocused-tiddler), which I believe is based on @felixhayashi 's [HotZone](https://tiddlymap.org/#%24%3A%2Fplugins%2Ffelixhayashi%2Fhotzone) plugin, but I argue this is of enough general interest and use, to be in the core.

**A few things that could be implemented if we have this:**

* [kodemo](https://kodemo.com/docs/what-is-kodemo) version
* ...[here is a rough demo](https://issue8478.tiddlyhost.com/) of this in TW, using the above plugin
* If I understand [this comment](https://github.com/TiddlyWiki/TiddlyWiki5/issues/2776#issuecomment-284336057) by @Jermolene (last sentence) the OP might also enable these:<br>-  #2776 <br>- #7262

**Some articles**
...outlining js implementations and elaborating on why this feature is useful:

* [article #1](https://phuoc.ng/collection/intersection-observer-with-react/check-if-an-element-is-visible-in-the-viewport/) (btw, one of his proposed use cases - "infinite scrolling" - may, in our case, perhaps be useful for lazy loading)
* [article #2](https://marco-prontera.medium.com/now-you-see-me-is-in-viewport-javascript-efa19b20b063)
* [jsfiddle](https://jsfiddle.net/zk36fg92/7/)

**Comment by Jermolene** [comment]
Hi @twMat the phrase "title of the tiddler currently seen in the viewport" needs a bit of unpacking. There are edge cases that will need to be considered carefully:

* What happens if there are more than one tiddler visible in the viewport? What happens to tiddlers that are partially visible?
* What happens if the input focus is in a different tiddler than the one currently focussed? For example, I can click into the text area of a tiddler editor and then scroll the page so that it is no longer visible, but it is still the active element and will receive any subsequent keyboard input

The dynaview plugin can already be used to track whether a tiddler is visible in the viewport. If you're happy to cater for the situation where multiple tiddlers can be marked as being visible then it could be used to satisfy the OP. If you want a single tiddler to be selected then we'd need to figure out those edge cases.

It's the potential clashes with the browser input focus that I think will be most difficult to resolve. There's no question but that keyboard shortcuts should apply to the tiddler that has input focus, and that would appear to clash with the idea of applying keyboard shortcuts to the tiddler currently in the viewport.

**Comment by twMat** [comment]
OK, fair questions that make me understand my request is very poorly defined, so I'm closing it to bring up for discussion on the forum instead. But regarding:

>The dynaview plugin ... could be used to satisfy the OP. 

This touches on a different problem: As a plugin author, it does not feel reasonable to force my plugin users to install *another* plugin. From *elsewhere*. Which I have *no control* over (what if it is upgraded and mine no longer is compatible?). And, at that, which is complex and does much more than the specific aspect needed for my plugin. Rather,  that this *is* featured in Dynaview supports the argument in the OP that, indeed, the feature is of general use and should therefore be in the core.

But, as noted, I need to define exactly what I mean with "this feature" ;-)

Thank you.

**Comment by Jermolene** [comment]
> This touches on a different problem: As a plugin author, it does not feel reasonable to force my plugin users to install _another_ plugin. From _elsewhere_. Which I have _no control_ over (what if it is upgraded and mine no longer is compatible?). And, at that, which is complex and does much more than the specific aspect needed for my plugin. Rather, that this _is_ featured in Dynaview supports the argument in the OP that, indeed, the feature is of general use and should therefore be in the core.

The core has backwards compatibility guarantees that minimise the risk. If it did become a problem it would be an argument in favour of moving the functionality into the core.
